# Simple Nginx PHP Base - Built On CentOS 6
FROM nginx:php5
MAINTAINER Geoffrey Harrison <geoffrey.harrison@lynxdigital.com.au>

ADD scripts/index.php /usr/share/nginx/html/index.php

ADD config/default.conf /etc/nginx/conf.d/default.conf

